---
- name: Install openvpn package
  ansible.builtin.dnf:
    name: openvpn
    state: present

- name: Generate openvpn secret key
  run_once: true
  ansible.builtin.include_tasks: genkey.yml

- name: Update openvpn secret key
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/{{ openvpn_key_local_path }}'
    dest: '{{ openvpn_key_remote_path }}'
    owner: root
    group: root
    mode: '0600'
  no_log: true
