---
- name: Restart service openconnect-{{ openconnect_profile }}
  ansible.builtin.systemd_service:
    name: openconnect-{{ openconnect_profile }}.service
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'
