---
- name: Install openconnect client
  ansible.builtin.dnf:
    name: openconnect
    state: present

- name: Create openconnect config directory
  ansible.builtin.file:
    path: /etc/openconnect
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate openconnect CA certificate
  ansible.builtin.include_role:
    name: tls_ca
  vars:
    tls_ca_remote_path: '{{ openconnect_ca_cert }}'

- name: Generate openconnect certificate and key
  ansible.builtin.include_role:
    name: tls_cert
  vars:
    tls_cert_cert: '{{ openconnect_cert }}'
    tls_cert_key: '{{ openconnect_key }}'

- name: Generate openconnect service for profile {{ openconnect_profile }}
  ansible.builtin.template:
    src: openconnect.service
    dest: /etc/systemd/system/openconnect-{{ openconnect_profile }}.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart service openconnect-{{ openconnect_profile }}

- name: Generate openconnect config for profile {{ openconnect_profile }}
  ansible.builtin.template:
    src: '{{ openconnect_profile }}.conf'
    dest: /etc/openconnect/{{ openconnect_profile }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart service openconnect-{{ openconnect_profile }}

- name: Enable and start service openconnect-{{ openconnect_profile }}
  ansible.builtin.systemd_service:
    name: openconnect-{{ openconnect_profile }}.service
    daemon_reload: true
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
