- name: Install required packages
  ansible.builtin.dnf:
    name:
      - openvpn
      - policycoreutils-python-utils
    state: present

- name: Allow openvpn to listen on port
  vars:
    openvpn_port: '{{ vars["openvpn_server_" + openvpn_profile + "_port"] |
      default(False) }}'
    openvpn_proto: '{{ vars["openvpn_server_" + openvpn_profile + "_proto"] |
      default(False) }}'
  community.general.seport:
    ports: '{{ openvpn_port }}'
    proto: '{{ openvpn_proto }}'
    setype: openvpn_port_t
    state: present
  when:
    - openvpn_profile_type == "server"
    - openvpn_port
    - openvpn_proto

- name: Update openvpn profile {{ openvpn_profile }}
  ansible.builtin.template:
    src: '{{ openvpn_profile_type }}/{{ openvpn_profile }}.conf'
    dest: /etc/openvpn/{{ openvpn_profile_type }}/{{ openvpn_profile }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart service {{ openvpn_service_name }}

- name: Enable and start service {{ openvpn_service_name }}
  ansible.builtin.systemd_service:
    name: '{{ openvpn_service_name }}.service'
    daemon-reload: true
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
